/**
 * Mobile database initialization using @capacitor-community/sqlite
 * with Drizzle ORM's sqlite-proxy driver.
 *
 * The sqlite-proxy driver lets us wrap any async SQLite implementation
 * with a simple callback. This bridges the Capacitor SQLite plugin's
 * async native API to Drizzle's query interface.
 */
import {
  CapacitorSQLite,
  SQLiteConnection,
  type SQLiteDBConnection,
} from "@capacitor-community/sqlite";
import { drizzle } from "drizzle-orm/sqlite-proxy";
import type { AppDb, RawSqliteDb } from "@swanki/core/db";
import * as schema from "@swanki/core/db/schema";

const sqlite = new SQLiteConnection(CapacitorSQLite);
const DB_NAME = "swanki";

/**
 * Apply migrations from the bundled migration files.
 * Generated by: cd apps/web && bun x drizzle-kit generate --config drizzle.config.mobile.ts
 */
async function applyMigrations(dbConn: SQLiteDBConnection): Promise<void> {
  // Create migration tracking table
  await dbConn.run(`
    CREATE TABLE IF NOT EXISTS __drizzle_migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      hash TEXT NOT NULL,
      created_at INTEGER NOT NULL
    )
  `);

  // Check which migrations have been applied
  const applied = await dbConn.query(
    "SELECT hash FROM __drizzle_migrations ORDER BY id",
  );
  const appliedHashes = new Set(
    (applied.values ?? []).map((row: unknown[]) => row[0] as string),
  );

  // Import inlined migrations (generated from drizzle-kit, inlined for Vite bundling)
  const { mobileMigrations } = await import("./migrations");
  const { journal, migrations } = mobileMigrations;

  for (const entry of journal.entries) {
    const hash = entry.tag;
    if (appliedHashes.has(hash)) {
      continue;
    }

    const sql = migrations[hash];
    if (!sql) {
      console.warn(`Migration SQL not found for: ${hash}`);
      continue;
    }

    // Split on semicolons and execute each statement
    const statements = sql
      .split(";")
      .map((s: string) => s.trim())
      .filter((s: string) => s.length > 0);

    for (const statement of statements) {
      await dbConn.run(statement);
    }

    // Record migration as applied
    await dbConn.run(
      "INSERT INTO __drizzle_migrations (hash, created_at) VALUES (?, ?)",
      [hash, Date.now()],
    );
  }
}

/**
 * Initialize the mobile SQLite database.
 *
 * Returns a Drizzle-compatible database instance (via sqlite-proxy driver)
 * and a raw SQLite handle for transaction control (used by ImportService).
 */
export async function initMobileDb(): Promise<{
  db: AppDb;
  rawDb: RawSqliteDb;
}> {
  // Check connection consistency
  const retCC = await sqlite.checkConnectionsConsistency();
  const retIsConn = await sqlite.isConnection(DB_NAME, false);

  let dbConn: SQLiteDBConnection;

  if (retCC.result && retIsConn.result) {
    dbConn = await sqlite.retrieveConnection(DB_NAME, false);
  } else {
    dbConn = await sqlite.createConnection(
      DB_NAME,
      false,
      "no-encryption",
      1,
      false,
    );
  }

  await dbConn.open();

  // Set pragmas
  await dbConn.run("PRAGMA journal_mode = WAL");
  await dbConn.run("PRAGMA foreign_keys = ON");

  // Apply migrations
  await applyMigrations(dbConn);

  // Create Drizzle instance using sqlite-proxy driver.
  // The callback receives SQL + params and must return rows.
  // - method 'run': INSERT/UPDATE/DELETE — returns empty rows
  // - method 'all': SELECT — returns rows as arrays of values
  // - method 'get': SELECT single row — returns single row
  const db = drizzle(
    async (sql, params, method) => {
      try {
        if (method === "run") {
          await dbConn.run(sql, params as unknown[]);
          return { rows: [] };
        }

        // SELECT query — Capacitor SQLite returns rows as array of objects
        // Drizzle sqlite-proxy expects rows as arrays of values
        const result = await dbConn.query(sql, params as unknown[]);
        const rawRows = result.values ?? [];

        // Convert array-of-objects to array-of-arrays
        if (
          rawRows.length > 0 &&
          typeof rawRows[0] === "object" &&
          !Array.isArray(rawRows[0])
        ) {
          const objectRows = rawRows as Record<string, unknown>[];
          const keys = Object.keys(objectRows[0]);
          const arrayRows = objectRows.map((row) => keys.map((k) => row[k]));
          return { rows: arrayRows };
        }

        return { rows: rawRows };
      } catch (e) {
        console.error("SQLite proxy error:", sql, e);
        return { rows: [] };
      }
    },
    { schema },
  ) as AppDb;

  // Raw DB interface for transaction control (ImportService)
  const rawDb: RawSqliteDb = {
    async execSQL(sql: string): Promise<void> {
      await dbConn.run(sql);
    },
  };

  return { db, rawDb };
}
